my_string = input()
print('Количество символов ', len(my_string))
print('В верхнем регистре ', my_string.upper())
print('В нижнем регистре ', my_string.lower())
print('Без пробелов', my_string.replace(' ', ''))
print('Первый символ строки ', my_string[0])
print('Последний символ строки ', my_string[-1])
